config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :comments
  resources :islands
  resources :buildings, :only => [:show]
  devise_for :users, controllers: { :sessions => "users/sessions", :registrations => "users/registrations"}
  root to: "hello#index"
  get "hello/home" => "hello#home"
  get "hello/profile" => "hello#profile"
  get "hello/ranking" => "hello#ranking"
  get "hello/shop" => "hello#shop"
  get "hello/tutorial" => "hello#tutorial"
  get "hello/introduction" => "hello#introduction"
  get "hello/show_user/:show_user_id" => "hello#show_user", :as => "hello_show_user"
  get "islands/show_island/:show_island_id" => "islands#show_island", :as => "islands_show_island"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :island
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/cowork.rb
class Cowork < ApplicationRecord
end

app/models/fav.rb
class Fav < ApplicationRecord
end

app/models/island.rb
class Island < ApplicationRecord
  has_many :buildings
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/resident.rb
class Resident < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Association(1:many)
  has_many :islands
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :omniauthable
  # def self.find_for_oauth(auth)
  #  user = User.where(uid: auth.uid, provider: auth.provider).first

  #  unless user
  #    user = User.create(
  #      uid:      auth.uid,
  #      provider: auth.provider,
  #      email:    auth.info.email,
  #      password: Devise.friendly_token[0, 20]
  #    )
  #  end

  #  user
  # end
end

app/models/wannado.rb
class Wannado < ApplicationRecord
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  before_action :authenticate_user!, only: [:home]

  def index
  end

  def home
    @buildings = Building.all
    render :layout => 'application2'
  end

  def profile
    @user = current_user
    render :layout => 'application2'
  end

  def ranking
    render :layout => 'application2'
  end

  def shop
    render :layout => 'application2'
  end

  def tutorial
    render :layout => 'application2'
  end

  def introduction
    render :layout => 'application2'
  end

  def show_user
    @user = User.find(params[:show_user_id])
    render :layout => 'application2'
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  before_action :set_island, only: [:show, :edit, :update, :destroy]

  # GET /islands
  # GET /islands.json
  def index
    @islands = Island.all
  end

  # GET /islands/1
  # GET /islands/1.json
  def show
  end

  def show_island
    @island = Island.find(params[:show_island_id])
    render :layout => 'application2'
  end

  # GET /islands/new
  def new
    @island = Island.new
  end

  # GET /islands/1/edit
  def edit
  end

  # POST /islands
  # POST /islands.json
  def create
    @island = Island.new(island_params)

    respond_to do |format|
      if @island.save
        format.html { redirect_to @island, notice: 'Island was successfully created.' }
        format.json { render :show, status: :created, location: @island }
      else
        format.html { render :new }
        format.json { render json: @island.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /islands/1
  # PATCH/PUT /islands/1.json
  def update
    respond_to do |format|
      if @island.update(island_params)
        format.html { redirect_to @island, notice: 'Island was successfully updated.' }
        format.json { render :show, status: :ok, location: @island }
      else
        format.html { render :edit }
        format.json { render json: @island.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /islands/1
  # DELETE /islands/1.json
  def destroy
    @island.destroy
    respond_to do |format|
      format.html { redirect_to islands_url, notice: 'Island was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_island
      @island = Island.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def island_params
      params.require(:island).permit(:name, :user_id, :description, :text, :icon)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/coworks_helper.rb
module CoworksHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/islands_helper.rb
module IslandsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/islands/_form.html.erb
<%= form_with(model: island, local: true) do |form| %>
  <% if island.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(island.errors.count, "error") %> prohibited this island from being saved:</h2>

      <ul>
      <% island.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :island_name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :island_user_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :island_description %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :island_text %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon, id: :island_icon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/islands/edit.html.erb
<h1>Editing Island</h1>

<%= render 'form', island: @island %>

<%= link_to 'Show', @island %> |
<%= link_to 'Back', islands_path %>

app/views/islands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Islands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Description</th>
      <th>Text</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @islands.each do |island| %>
      <tr>
        <td><%= island.name %></td>
        <td><%= island.user_id %></td>
        <td><%= island.description %></td>
        <td><%= island.text %></td>
        <td><%= island.icon %></td>
        <td><%= link_to 'Show', island %></td>
        <td><%= link_to 'Edit', edit_island_path(island) %></td>
        <td><%= link_to 'Destroy', island, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Island', new_island_path %>

app/views/islands/new.html.erb
<h1>New Island</h1>

<%= render 'form', island: @island %>

<%= link_to 'Back', islands_path %>

app/views/islands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @island.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @island.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @island.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @island.text %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @island.icon %>
</p>

<%= link_to 'Edit', edit_island_path(@island) %> |
<%= link_to 'Back', islands_path %>

app/views/islands/show_island.html.erb
<div class="container" style="padding-top:150px;">

  <div class="row show-top">
    <div class="col-xs-12 show-top-picture-container">
      <div class="show-top-picture debug-background">

      </div>
    </div>
    <div class="col-xs-12 island-top-name">
      <%= @island.name %>
    </div>
  </div>

  <div class="row island-follow">
    <div class="col-xs-12 island-follow-name">
      Resident : <%= "65" %>
    </div>
    <div class="col-xs-12 island-follow-list">
    </div>
  </div>
  <div class="row island-profile">
    <div class="col-xs-12 island-profile-name">
      Description
    </div>
    <div class="col-xs-12 island-profile-desc">
      <%= @island.description %>
    </div>
  </div>

  <div class="row show-island">
    <div class="col-xs-12 show-island-name">
      Buildings
    </div>
    <div class="island-building-container">
      <% @island.buildings.each do |building| %>
        <div class="bcard">
          <div class="bcard-top">
            <div class="bcard-name">
              <p class="bcard-island">
                <b><%= building.title %></b><br>
              </p>
            </div>
          </div>
          <p class="bcard-text">
            <%= building.description %>
          </p>
          <div class="bcard-image debug-background3">
          </div>
          <div class="bcard-button-container container">
            <div class="row">
              <div class="col-xs-4 btn">
                Wanna Do!
              </div>
              <div class="col-xs-4 btn">
                Like
              </div>
              <div class="col-xs-4 btn">
                Comment
              </div>
            </div>
            <div class="row">
              <div class="col-xs-4 counter">
                5
              </div>
              <div class="col-xs-4 counter">
                34
              </div>
              <div class="col-xs-4 counter">
                12
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>