config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :comments
  resources :islands
  resources :buildings, :only => [:show]
  devise_for :users, controllers: { :sessions => "users/sessions", :registrations => "users/registrations"}
  root to: "hello#index"
  get "hello/home" => "hello#home"
  get "hello/profile" => "hello#profile"
  get "hello/ranking" => "hello#ranking"
  get "hello/shop" => "hello#shop"
  get "hello/tutorial" => "hello#tutorial"
  get "hello/introduction" => "hello#introduction"
  get "hello/show_user/:show_user_id" => "hello#show_user", :as => "hello_show_user"
  get "islands/show_island/:show_island_id" => "islands#show_island", :as => "islands_show_island"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :island
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/cowork.rb
class Cowork < ApplicationRecord
end

app/models/fav.rb
class Fav < ApplicationRecord
end

app/models/island.rb
class Island < ApplicationRecord
  has_many :buildings
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/resident.rb
class Resident < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Association(1:many)
  has_many :islands
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :omniauthable
  # def self.find_for_oauth(auth)
  #  user = User.where(uid: auth.uid, provider: auth.provider).first

  #  unless user
  #    user = User.create(
  #      uid:      auth.uid,
  #      provider: auth.provider,
  #      email:    auth.info.email,
  #      password: Devise.friendly_token[0, 20]
  #    )
  #  end

  #  user
  # end
end

app/models/wannado.rb
class Wannado < ApplicationRecord
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :building_id, :comment)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  before_action :authenticate_user!, only: [:home]

  def index
  end

  def home
    @buildings = Building.all
    render :layout => 'application2'
  end

  def profile
    @user = current_user
    render :layout => 'application2'
  end

  def ranking
    render :layout => 'application2'
  end

  def shop
    render :layout => 'application2'
  end

  def tutorial
    render :layout => 'application2'
  end

  def introduction
    render :layout => 'application2'
  end

  def show_user
    @user = User.find(params[:show_user_id])
    render :layout => 'application2'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/coworks_helper.rb
module CoworksHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/islands_helper.rb
module IslandsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :building_id %>
    <%= form.number_field :building_id, id: :comment_building_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :comment_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Building</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.building_id %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Building:</strong>
  <%= @comment.building_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>