config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :comments
  resources :islands
  resources :buildings, :only => [:show]
  devise_for :users, controllers: { :sessions => "users/sessions", :registrations => "users/registrations"}
  root to: "hello#index"
  get "hello/home" => "hello#home"
  get "hello/profile" => "hello#profile"
  get "hello/ranking" => "hello#ranking"
  get "hello/shop" => "hello#shop"
  get "hello/tutorial" => "hello#tutorial"
  get "hello/introduction" => "hello#introduction"
  get "hello/show_user/:show_user_id" => "hello#show_user", :as => "hello_show_user"
  get "islands/show_island/:show_island_id" => "islands#show_island", :as => "islands_show_island"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :island
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/cowork.rb
class Cowork < ApplicationRecord
end

app/models/fav.rb
class Fav < ApplicationRecord
end

app/models/island.rb
class Island < ApplicationRecord
  has_many :buildings
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/resident.rb
class Resident < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Association(1:many)
  has_many :islands
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :omniauthable
  # def self.find_for_oauth(auth)
  #  user = User.where(uid: auth.uid, provider: auth.provider).first

  #  unless user
  #    user = User.create(
  #      uid:      auth.uid,
  #      provider: auth.provider,
  #      email:    auth.info.email,
  #      password: Devise.friendly_token[0, 20]
  #    )
  #  end

  #  user
  # end
end

app/models/wannado.rb
class Wannado < ApplicationRecord
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:title, :description, :image, :island_id, :deadline)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  before_action :authenticate_user!, only: [:home]

  def index
  end

  def home
    @buildings = Building.all
    render :layout => 'application2'
  end

  def profile
    @user = current_user
    render :layout => 'application2'
  end

  def ranking
    render :layout => 'application2'
  end

  def shop
    render :layout => 'application2'
  end

  def tutorial
    render :layout => 'application2'
  end

  def introduction
    render :layout => 'application2'
  end

  def show_user
    @user = User.find(params[:show_user_id])
    render :layout => 'application2'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/coworks_helper.rb
module CoworksHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/islands_helper.rb
module IslandsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/buildings/_form.html.erb
<%= form_with(model: building, local: true) do |form| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :building_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :building_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :building_image %>
  </div>

  <div class="field">
    <%= form.label :island_id %>
    <%= form.number_field :island_id, id: :building_island_id %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline, id: :building_deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th>Island</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.title %></td>
        <td><%= building.description %></td>
        <td><%= building.image %></td>
        <td><%= building.island_id %></td>
        <td><%= building.deadline %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<%
  island_user = Island.find(@building.island.id)
%>

<div class="bcard-modal">
  <div class="bcard-top">
    <div class="bcard-icon debug-background2">
    </div>
    <div class="bcard-name">
      <p class="bcard-island">
        <b><%= @building.title %></b><br>
        <span class="bcard-address">Address: <%= @building.island.name %> / <%= @building.island.user.name %></span>
      </p>
    </div>
  </div>
  <p class="bcard-text">
    <%= @building.description %>
  </p>
  <div class="bcard-image debug-background3">
  </div>
  <div class="bcard-button-container container">
    <div class="row">
      <div class="col-xs-4 btn">
        Wanna Do!
      </div>
      <div class="col-xs-4 btn">
        Like
      </div>
      <div class="col-xs-4 btn">
        Comment
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4 counter">
        5
      </div>
      <div class="col-xs-4 counter">
        34
      </div>
      <div class="col-xs-4 counter">
        12
      </div>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>