config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :comments
  resources :islands
  resources :buildings, :only => [:show]
  devise_for :users, controllers: { :sessions => "users/sessions", :registrations => "users/registrations"}
  root to: "hello#index"
  get "hello/home" => "hello#home"
  get "hello/profile" => "hello#profile"
  get "hello/ranking" => "hello#ranking"
  get "hello/shop" => "hello#shop"
  get "hello/tutorial" => "hello#tutorial"
  get "hello/introduction" => "hello#introduction"
  get "hello/show_user/:show_user_id" => "hello#show_user", :as => "hello_show_user"
  get "islands/show_island/:show_island_id" => "islands#show_island", :as => "islands_show_island"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :island
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/cowork.rb
class Cowork < ApplicationRecord
end

app/models/fav.rb
class Fav < ApplicationRecord
end

app/models/island.rb
class Island < ApplicationRecord
  has_many :buildings
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/resident.rb
class Resident < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Association(1:many)
  has_many :islands
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :omniauthable
  # def self.find_for_oauth(auth)
  #  user = User.where(uid: auth.uid, provider: auth.provider).first

  #  unless user
  #    user = User.create(
  #      uid:      auth.uid,
  #      provider: auth.provider,
  #      email:    auth.info.email,
  #      password: Devise.friendly_token[0, 20]
  #    )
  #  end

  #  user
  # end
end

app/models/wannado.rb
class Wannado < ApplicationRecord
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  before_action :authenticate_user!, only: [:home]

  def index
  end

  def home
    @buildings = Building.all
    render :layout => 'application2'
  end

  def profile
    @user = current_user
    render :layout => 'application2'
  end

  def ranking
    render :layout => 'application2'
  end

  def shop
    render :layout => 'application2'
  end

  def tutorial
    render :layout => 'application2'
  end

  def introduction
    render :layout => 'application2'
  end

  def show_user
    @user = User.find(params[:show_user_id])
    render :layout => 'application2'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:building_id, :report)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/coworks_helper.rb
module CoworksHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/islands_helper.rb
module IslandsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :building_id %>
    <%= form.number_field :building_id, id: :report_building_id %>
  </div>

  <div class="field">
    <%= form.label :report %>
    <%= form.text_area :report, id: :report_report %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Building</th>
      <th>Report</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.building_id %></td>
        <td><%= report.report %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building:</strong>
  <%= @report.building_id %>
</p>

<p>
  <strong>Report:</strong>
  <%= @report.report %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>